# Nested for loop 

In [1]:
import numpy as np
from fractions import Fraction
from decimal import Decimal

In [2]:
for i in xrange(0,3):
    for j in  xrange(0,3):
        print 'i = %d'  %i
        print 'j = %d'  %j
        print

i = 0
j = 0

i = 0
j = 1

i = 0
j = 2

i = 1
j = 0

i = 1
j = 1

i = 1
j = 2

i = 2
j = 0

i = 2
j = 1

i = 2
j = 2



In [3]:
M = np.zeros((4,3))
print M
print

for i in xrange(0,4):
    for j in  xrange(0,3):
        M[i,j] = i
print M

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [4]:
M = np.zeros((4,3))
print M
print

for i in xrange(0,4):
    for j in  xrange(0,3):
        M[i,j] = (i+1)*(j+1)
print M

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[ 1.  2.  3.]
 [ 2.  4.  6.]
 [ 3.  6.  9.]
 [ 4.  8. 12.]]


In [5]:
s = 5  #s represents the size of the Hilbert matrix
M = np.zeros((s,s))

for i in xrange(1,s+1):
    for j in  xrange(1,s+1):
        M[i-1,j-1] = 1.0/(i+j-1)
print M

[[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]]


# Matrix multiplication

In [6]:
a = np.array( [[1, 0],  [0, 1]] )

b = np.array([1, 2])

np.matmul(a, b)



array([1, 2])

In [7]:
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1], 
              [2, 2]])
np.matmul(a, b)

array([[4, 1],
       [2, 2]])

In [8]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[1, 2], 
              [2, 3]])
np.matmul(a, b)

array([[ 5,  8],
       [11, 18]])

In [9]:
np.matmul(b, a)

array([[ 7, 10],
       [11, 16]])